language: python
python:
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: releases
  api_key:
    secure: jfNebcOuFI96w0VacMuo7MD8qCpK2FyntJgPY7i7kYFYBAUR+UKX23w8qa9hCw6wiTWxHJBtH2uD04Z7RokwCxSMoaEFVmA+33ode9eiAaP6oy0JHXOe8hr5Xa9uo2MOWz9XAXmgfGCI9mv8VosN+dIsamH5qavmw6iCNYwCOMcBJwyf1GtuILVRJ/MMNYhJ+09AiEZFff1w7VhhxhsZbZxV3qgZjTwJyWfXKvcVMDwKpIodqp+Vv9LO96w68hBNArXgCUlLZoSBe22GGpx2Mvcs0jZGNhly5rKWaJulNnqd6ifbdCNQi5i6lHwGKXgWHjJYjMe+wPUmtGkH7BeKWSanP+De2+wllqU3PxRSlhmFVRTB186bRZ57vhvmxNjehiSU51B+ds181v2tZXKNeb8Tb46aASgR3nywIN+S+KuQ61lQiNSzm8Nfs6l+VVoWmC/8Ps64kqGMEN23lJ2Wi/ZoO3hitFhUHsOd8CabSRnPXs2zSRqeSejCIycz1kPSOQKTawoLNcJC9YPOMRCrPSljtaMZtHdz3KCKzLPeYEN65/iOuw2KThfgTwtwYY/uAdKf98Sp+ef0jvOSERlZzKHyBdGMUcbffV0GF1YW6/llfdaqlxESpY3gr7jAzmxtxPF7MZsgRYgjNeYXUmDIMulfYfWqaheKhye+056QJEA=
  file_glob: true
  file: /dist/*.whl
  skip_cleanup: true
  on:
    repo: dotEsuS/e_ok_api
    tags: true
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dotEsuS
  password:
    secure: TK9CYIkQLuEzNKdhkk/VxCVCCymntLj6Qdk5i5i9IQNGxC1R1vtNuS4+bBPDaY7VzmAYcegAfSXV4RdO+gsNgdqNEu8++lF3JslN0NXe8oy5qD/93KtcSJ4cSFHYIKx3gWKZMNJrKaFxT5tVWKg+zL3ZTL2/2yaFFGkj400NSkkvZgh7WuQuS7wFRODnIgfJ5PPTsCy7n1Jvt/x3ZmbP01tKzvRsxQaP6b72TzjoTe6YREJjHbRHVdXYYuc7o7/HFP816d3ynnx6TTSfoKdWAUaPBK8fba0Tjea6lwxqC3NvLXexc4FGyf74P9hbTHMp3sQmJQFMDLMQ7WrOWawPfF8q99xjsoPrJJ7EIH/+3sC+h4mW/JVeJ8QarZMCBi6amod93hGiwVi08iptnOPjR3CfoS5yVc4kgSNFx3kIM3S+ZqrgRHgYM4MOIrTDvb6xiZlDjxm5ObmdqGv0w4or+oQ7z+1WAPoccWUqgcYtuX8a9SetBuZrX+ZfmF6XlGmhyjipDjn79joNo3FoW1Vk9bW8bLD7572lVzaTavIWYMmdV7/aWY5vQPFh/7sRgGyQ4hIB1HLK8gPc3nyjpmX+yWKWUCCiis+VPI7lcqAN+cq+LgwXkprzcvBqPAeHZE2SjOShDqdC38mh/GR7vvdXr25UwBujIKDbwaZsOyKmpfo=
  on:
    tags: true
    repo: dotEsuS/e_ok_api
    python: 3.6
